# Generated by Django 4.2.7 on 2024-01-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='foodwishlist',
            name='quantity',
        ),
    ]
